### ISSUE TITLE
Tributary support

### ISSUE THREAD

**Issue by ishidawataru** [Telecominfraproject/oopt-tai#12]
I'm thinking of adding tributary support in TAI.
At first, I’d like to check if I understand https://github.com/Telecominfraproject/oopt-tai/pull/1 correct.

Tributary support will enable flexible mapping of host interfaces and network interfaces.

For example, Facebook Voyager has 2 Acacia AC400 inside. AC400 is a dual channel module and can transport 3x100G client signal. When modeling this with TAI, we would have 2 [network interfaces](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/tainetworkif.h#L230) and 3 [host interfaces](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/taihostif.h#L118) inside 1 [module](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/taimodule.h#L284).

TAI already has 

[TAI_MODULE_ATTR_NUM_HOST_INTERFACES](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/taimodule.h#L216) and [TAI_MODULE_ATTR_NUM_NETWORK_INTERFACES](https://github.com/Telecominfraproject/oopt-tai/blob/master/inc/taimodule.h#L224) to let the adapter host know how many host interfaces and network interfaces a module has.

However, current TAI master branch lacks attributes for the mapping of host interfaces and network interfaces.

https://github.com/Telecominfraproject/oopt-tai/pull/1 adds some attributes for this purpose.

This PR adds `TAI_MODULE_ATTR_NETWORK_MODE` which switches how the module exposes the network interfaces inside it.

In case of AC400, if the attribute is set to `TAI_MODULE_NETWORK_MODE_INDEPENDENT`, 2 network interfaces will be exposed. if set to `TAI_MODULE_NETWORK_MODE_COUPLED`, only 1 network interface will be exposed. 

Based on this attribute, the adapter host will use 

- `TAI_HOST_INTERFACE_ATTR_INDEP_RX_NETWORK_TRIBUTARY`
- `TAI_NETWORK_INTERFACE_ATTR_INDEP_TX_CLIENT_TRIBUTARY`

or

- `TAI_HOST_INTERFACE_ATTR_COUPLED_RX_NETWORK_TRIBUTARY`
- `TAI_NETWORK_INTERFACE_ATTR_COUPLED_TX_CLIENT_TRIBUTARY`

to set the mapping.

Since RX/TX mapping attribute is separated, we could map RX and TX with different host/network interface pairs.

@scott-emery Could you check if I'm wrong?

**Comment by scott-emery** [comment]
Wow. Your understanding is very good. Everything you said is correct. The only exception is that I didn't alter the number of network interfaces or host interfaces based on the configuration. There are always 4 host interfaces and 2 network interfaces exposed through TAI for each AC400 module.

In some modulation settings some of the host interfaces are not used, but all 4 are always present via TAI. The same holds true for the network interfaces: there are always 2 exposed through TAI, even though in coupled mode they both operate together and only the configuration applied to the first network interface alters the coupled network interface behavior. You can still get/modify attributes on the second network interface, but modifications don't change the operation.

As far as tributaries go, the idea is that you can flexibly connect the host interfaces to the network interfaces, and network interfaces to host interfaces. The configuration is even flexible enough to allow different mappings in both directions. Personally, I see this as a low priority, simply because these systems have transponders connected to switching silicon. The switching silicon can direct traffic to different host interfaces in a much more flexible way than the static MUXes on the AC400 module.

**Comment by ishidawataru** [comment]
@scott-emery I opened a PR to add an attribute in `taimodule` for the mapping of netif and hostif.
Just like your original approach, this approach also doesn't change the number of netif and hostif.

However, since this approach doesn't have a notion of  'coupled' / 'de-coupled', it is the adapter host responsibility to correctly configure both netifs.

Also, this approach doesn't have the flexibility to allow different mappings in both directions for now.
We could add an additional attribute whose key is hostif and value is a list of netif to support this. But I think only one attribute is simple and good enough.
