### ISSUE TITLE
Loopback Support

### ISSUE THREAD

**Issue by scott-emery** [Telecominfraproject/oopt-tai#18]
It is common for network operators to test the optical line system by placing a network interface in loopback, sending data to that interface from a far-end system, and checking the data received back on that far-end system.

I would like to add a loopback attribute to network interfaces. Setting this attribute to true will cause all data received on the network interface to be sent back out on the same network interface.

And just for good measure, I would also like to add a host interface loopback. When enabled, this would send all data received on a host interface back out that same host interface.

Does this seem valuable?

Is a boolean value the appropriate type for these attributes? I could imagine transponders where different types of loopback are supported (optical loopback, digital loopback, etc.). Is that overkill? The MSA MIS appears to only allow enable/disable. If different types of loopback should be supported, are there references for the types of loopbacks typically supported?

**Comment by ishidawataru** [comment]
https://github.com/OpenROADM/OpenROADM_MSA_Public/blob/3e90fb1dcef7e989ecb5420fa6934b0c34b32a6e/model/Device/org-openroadm-maintenance-loopback.yang#L47-L80

OpenROADM has two loopback types for network side. 

https://github.com/openconfig/public/blob/aea5b1525f9e1ed439924ccc5debaae092e1f3f8/release/models/optical-transport/openconfig-transport-types.yang#L73-L95

OpenConfig has only enable/disable.

How about starting with boolean and see if we need more granular setting?

BTW, should the change of the loopback attribute incur some status change?
I'd also like to clarify the relationship with PRBS enable/disable and loopback attribute since these two attributes would be used in conjunction.

**Comment by scott-emery** [comment]
Ok. We will start with a boolean and change it if needed. I think the two loopbacks in OpenConfig are actually what I proposed. The Facility and Terminal loopbacks are the loopback of the network interface object and host interface object(s). 

The only status change I was thinking about was that the loopback attribute of the network interface or host interface object would change. The same states of the interfaces (up/down/etc.) apply for loopbacked interfaces so I wouldn't want to change an interface state to "loopback", because that would hide the actual interface status.

PRBS, although commonly used in conjunction with loopback, is actually an independent thing. You can put an interface in loopback and send whatever data you want to test the loopback path. It doesn't have to be PRBS data. So I'd like to keep loopback and PRBS separate. Now, having said that, I expect that my next Issue here will be for adding PRBS to TAI.

**Comment by samisaab** [comment]
Hi.  Some DSPs provide shallow and deep loopback options, like the pre/post FEC options shown in the OpenROADM link above.  These options are useful both for facility and terminal loopbacks.  The purpose is to isolate a problem between the optical and digital link.  I agree that both options should be provided when setting the loopback mode.  Thanks.
