### ISSUE TITLE
Custom Attribute Range Request for Oclaro CFP2-ACO

### ISSUE THREAD

**Issue by samisaab** [Telecominfraproject/oopt-tai#44]
Would like to add Oclaro CFP2-ACO range in inc/tainetworkif.h as follows.

    /** Custom range for the TRB100 adapter */
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_TRB100_START = TAI_NETWORK_INTERFACE_ATTR_CUSTOM_AC400_END + 0x0001,
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_TRB100_END   = TAI_NETWORK_INTERFACE_ATTR_CUSTOM_TRB100_START + 0xFFFF,

**Comment by scott-emery** [comment]
@samisaab  Can you remove the initializer for the "START" value? I think it would be less error prone, long term, if the start values just follow the previous value. The only reason I initialized the AC400's "START" value was because I didn't want it to be +1 of the custom range start.

Also, there was some discussion at the workshop that each ACO module would, potentially, need different custom attributes for each DSP they are paired with. And so someone said that the ranges would need to be allocated for each DSP/ACO combination. Are you thinking that you will just manage custom attributes yourself, for each DSP, within your 64K range?

Other than that, sounds good to me.

**Comment by samisaab** [comment]
@scott-emery Sounds good.  I was thinking to keep all Oclaro CFP2-ACO custom attributes in one defined range, but your comment and further thought convinces me otherwise.  Following is an updated range definition.  @ishidawataru Let me know if you're good with this definition and range.

    /** Custom range for the NLD0670APB/TRB100 adapter */
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_START,
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_END = TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_START + 0xFF,

**Comment by scott-emery** [comment]
Can we keep all custom attribute allocations at 64K for now? I know it is TOTAL overkill. But we can define over 60,000 custom attribute ranges, each with space for 64K attributes. By defining a range of only 256 we may run into a situation where the next transceiver allocates 64K and thus those attributes are not so easy to determine which range they are a part of. If all attribute ranges are 64K then it is very easy to determine which range the attribute belongs to, when displayed as hex.

**Comment by samisaab** [comment]
Sounds good.

    /** Custom range for the NLD0670APB/TRB100 adapter */
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_START,
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_END = TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670APB_TRB100_START + 0xFFFF,

**Comment by ishidawataru** [comment]
@samisaab Please change `NLD0670APB` to `NLD0670`. NEL has several types of `NLD0670` chip which all have the same register map.

other than that LGTM. please open an PR.

**Comment by samisaab** [comment]
Will do.

    /** Custom range for the NLD0670APB/TRB100 adapter */
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670_TRB100_START,
    TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670_TRB100_END = TAI_NETWORK_INTERFACE_ATTR_CUSTOM_NLD0670_TRB100_START + 0xFFFF,
